Sample agerror
ss3sim/ss3sim pull request #400
Opened 2022-10-06 01:19 UTC by chamberlindw

@kellijohnson-NOAA 

Added a function to change the ageing error definition applied to fleet specific age composition data in the EM. Also added documentation for the function, tests in the testthat files, and added a small blurb in the introduction vignette with an example of running the run_ss3sim function in parallel with the parSapply( ) function.

2024-03-26 04:18 UTC, kellijohnson-NOAA commented
@chamberlindw I have not forgotten about this but I am not sure if I am going to be able to get to it this week. Sorry for the delay. I will for sure look at it next week.

2026-02-16 21:55 UTC, TEHinshaw requested changes
This code is looking great! A few items need attention before merging.


Critical:
1. r4ss changed column names (`FltSvy` -> `fleet`, `Ageerr` -> `ageerr`). Code needs to be updated accordingly.


Recommended: 
1. Add input validation for `fleets`/`definition` lenth mismatch
2. Use `seq_along(fleets)` instead of `1:length(fleets)`
3. Move validation outside loop to prevent partial modifications


Minor / Nitpicky:
1. Fix typo
2. Fix test names
3. Standardize "ageing" spelling

2026-02-16 21:55 UTC, TEHinshaw commented on R/change_em_ageerr.R
> +definition) {
Minor: consider adding a length check for fleets and definition, in case user incorrectly calls mismatched vectors.
```suggestion
definition) {
  if (length(fleets) != length(definition)) {
    stop("'fleets' and 'definition' must be the same length.")
  }
```

2026-02-16 21:55 UTC, TEHinshaw commented on R/change_em_ageerr.R
> +        # error deifnition
```suggestion
        # error definition
```

2026-02-16 21:55 UTC, TEHinshaw commented on tests/testthat/test-change-em-ageerr.R
> +test_that("change_em_err works as expected", {
I think this should be ageerr
```suggestion
test_that("change_em_ageerr works as expected", {
```

2026-04-08 03:14 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' Change aging error matrix in estimation model age composition
```suggestion
#' Change ageing-error matrix in estimation model
```

2026-04-08 03:15 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' Change aging error matrix in estimation model age composition
thank you @TEHinshaw for the suggestion! I will make this change.

2026-04-08 03:19 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' according to the user's specification.
```suggestion
#' This function alters the fleet-specific aging-error definition in a
#' Stock Synthesis estimation model (EM). Ageing error can only be modified
#' not changed so be sure to add ageing-error definitions to your EM prior
#' to running the simulation. Ageing error can have zero bias and exact
#' precision.
```

2026-04-08 03:19 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' for fleet specific changes to  aging error observations, not year specific.
```suggestion
#' for fleet-specific changes to  aging-error observations, not year specific.
```

2026-04-08 03:22 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' the `fleets` vector should correspond to the intended new aging error
```suggestion
#' the `fleets` vector should correspond to the intended new aging-error 
```

2026-04-08 03:23 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' definition in the `definition` vector. Currently this function only allows
```suggestion
#' definition in the `definition` argument. Currently this function only allows
```

2026-04-08 03:23 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' for fleet specific changes to  aging error observations, not year specific.
```suggestion
#' for fleet specific changes to  ageing-error observations, not year specific.
```

2026-04-08 03:25 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' and does not allow a new aging error matrix to be added.
```suggestion
#' Users need to input all ageing-error matrices being considered into the 
#' operating model (OM) data file, as this function changes an ageing-error 
#' definition in the age-composition section of the `dat` file and does not
#' allow a new ageing-error matrix to be added.
```

2026-04-08 03:36 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' and 2 in the second scenario.
```suggestion
#' Ageing-error definitions can also be changed in the OM in [run_ss3sim()] 
#' by inputting a vector of ageing-error definitions that you want to use for
#' fleet-specific sampling of the data. Each value in the provided vector
#' corresponds to the definition you want to use for a scenario. For example,
#' if the column labeled `sa.Ageerr.1` in `simdf` data frame equals 3 and 2,
#' then the ageing-error definitions for fleet 1 will be 3 in the first scenario
# and 2 in the second scenario.
```

2026-04-08 03:36 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' An entry of `fleets=NULL` leads to no ageing error definitions being
```suggestion
#' An entry of `fleets=NULL` leads to no ageing-error definitions being 
```

2026-04-08 03:38 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' error definitions must already input in the operating model (OM) data file.
```suggestion
#' @param definition A vector of integers, the same length as `fleets`, 
#' specifying the aging-error definitions to use for each fleet. The order of the 
#' definitions corresponds to the order of the `fleets` argument. The aging- 
#' error definitions must already be defined in the operating model (OM) data file.
```

2026-04-08 03:43 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' dat_list$ageerror <- rbind(dat_list$ageerror,dat_list$ageerror)
This PR updates that file to have two definitions by default but I am unsure if we should change this code here or not change the default OM dat file. I will have to come back to this.

2026-04-08 03:44 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' # An example changing the aging error observation for multiple fleets
```suggestion
#' # An example changing the ageing-error observation for multiple fleets
```

2026-04-08 03:46 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' of fleet 1 to 3 in the first scenario and 2 in the second scenario.
```suggestion
#' This function can also be called in [run_ss3sim()] by inputting a vector of
#' ageing-error definitions, corresponding to the ageing-error definition in each 
#' scenario, into a column labeled `ca.definition.1` in the `simdf` data frame. 
#' Where the number in `ca.definition.#` corresponds to the fleet. e.g.- 
#' `ca.definition.1 <- c(3, 2)` will change the aging-error definition, in the EM, 
#' of fleet 1 to 3 in the first scenario and 2 in the second scenario.
```

2026-04-08 03:47 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' # Adding in second aging error definition to the data file
```suggestion
#' # Adding in second ageing-error definition to the data file
```

2026-04-08 03:47 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +#' # An example changing the aging error observations for a single fleet
```suggestion
#' # An example changing the ageing-error observations for a single fleet
```

2026-04-08 03:47 UTC, kellijohnson-NOAA commented on R/change_em_ageerr.R
> +        # Lookup fleets to be changed and change aging
```suggestion
        # Lookup fleets to be changed and change ageing-
```

2026-04-13 16:27 UTC, merged

2026-04-13 16:28 UTC, kellijohnson-NOAA commented
@chamberlindw thank you again for your patience with this and for not giving up on me 😁 and thank you @TEHinshaw for the review to get things going.